development:
  host: <%= ENV['DATABASE_HOST'] %>
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
production:
  url: <%= ENV['DATABASE_URL'] %>